# Name your project
name: 'data_engineering_project'
version: '1.0.0'

profile: 'data_engineering_project'

# Specify the paths for different types of files
model-paths: ["models"]          # Path for your models
analysis-paths: ["analyses"]    # Path for your analyses
test-paths: ["tests"]            # Path for your tests
seed-paths: ["seeds"]            # Path for your seed files
macro-paths: ["macros"]          # Path for your macros
snapshot-paths: ["snapshots"]    # Path for your snapshots

# Clean targets to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models for each target
models:
  data_engineering_project:
    weather:
      weather_cleaned:
        +materialized: table  # Materialized as a table in the combined DuckDB database

    consumption_cleaned:
      +materialized: table  # Materialized as a table in the combined DuckDB database

    price_cleaned:
      +materialized: table  # Materialized as a table in the combined DuckDB database

    production_cleaned:
      +materialized: table  # Materialized as a table in the combined DuckDB database
