data_engineering_project:
  target: combined
  outputs:
    combined:
      type: duckdb
      threads: 1
      # Path to the combined DuckDB database
      path: "./mnt/tmp/duckdb_data/combined_data.duckdb"
